name: procpr
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - ld_impl_linux-64=2.43
  - libblas=3.9.0
  - libcblas=3.9.0
  - libexpat=2.7.0
  - libffi=3.4.6
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgfortran=14.2.0
  - libgfortran5=14.2.0
  - libgomp=14.2.0
  - liblapack=3.9.0
  - liblzma=5.6.4
  - libnsl=2.0.1
  - libopenblas=0.3.29
  - libsqlite=3.49.1
  - libstdcxx=14.2.0
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.4.1
  - pip=25.0.1
  - python=3.11.11
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.11
  - pytz=2024.1
  - readline=8.2
  - scikit-learn=1.6.1
  - scipy=1.15.2
  - setuptools=75.8.2
  - six=1.17.0
  - threadpoolctl=3.6.0
  - tk=8.6.13
  - tzdata=2025b
  - wheel=0.45.1
  - pip:
      - absl-py==2.2.2
      - accelerate==0.21.0
      - aiofiles==23.2.1
      - aiohttp==3.8.5
      - aiosignal==1.3.1
      - altair==5.1.2
      - annotated-types==0.7.0
      - anyio==3.7.1
      - appdirs==1.4.4
      - async-timeout==4.0.3
      - attrs==23.1.0
      - bitsandbytes==0.40.0
      - cachetools==5.5.0
      - certifi==2022.12.7
      - charset-normalizer==2.1.1
      - click==8.1.7
      - cmake==3.25.0
      - contourpy==1.1.1
      - cycler==0.12.1
      - datasets==2.14.4
      - deepspeed==0.16.4
      - dill==0.3.7
      - distro==1.9.0
      - docker-pycreds==0.4.0
      - docstring-parser==0.16
      - einops==0.6.1
      - evaluate==0.4.2
      - fastapi==0.103.2
      - ffmpy==0.3.1
      - filelock==3.13.1
      - flash-attention==1.0.0
      - flash-attn==2.3.2
      - fonttools==4.43.1
      - frozenlist==1.4.0
      - fsspec==2023.6.0
      - gradio==3.47.1
      - gradio-client==0.6.0
      - h11==0.14.0
      - hjson==3.1.0
      - httpcore==0.18.0
      - httpx==0.25.0
      - huggingface-hub==0.17.3
      - idna==3.4
      - importlib-resources==6.5.2
      - jinja2==3.1.2
      - jiter==0.8.2
      - joblib==1.3.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - kiwisolver==1.4.8
      - lit==15.0.7
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.8.0
      - mdurl==0.1.2
      - mpmath==1.3.0
      - msgpack==1.1.0
      - multidict==6.0.4
      - multiprocess==0.70.15
      - networkx==3.3
      - ninja==1.11.1.4
      - nltk==3.8.1
      - numpy==1.26.4
      - nvidia-ml-py==12.570.86
      - orjson==3.10.16
      - packaging==24.2
      - pandas==2.0.3
      - peft==0.4.0
      - pillow==10.4.0
      - propcache==0.3.1
      - protobuf==4.24.2
      - psutil==7.0.0
      - py-cpuinfo==9.0.0
      - pyarrow==19.0.1
      - pydantic==2.11.2
      - pydantic-core==2.33.1
      - pydub==0.25.1
      - pygments==2.19.1
      - pyparsing==3.2.3
      - python-multipart==0.0.20
      - pyyaml==6.0.2
      - referencing==0.36.2
      - regex==2024.11.6
      - requests==2.32.3
      - rich==13.9.4
      - rpds-py==0.24.0
      - safetensors==0.5.3
      - semantic-version==2.10.0
      - sentencepiece==0.1.99
      - sniffio==1.3.1
      - starlette==0.27.0
      - sympy==1.13.1
      - tokenizers==0.14.1
      - toolz==1.0.0
      - torch==2.0.1+cu117
      - torchaudio==2.0.2+cu117
      - torchvision==0.15.2+cu117
      - tqdm==4.67.1
      - transformers==4.34.0
      - triton==2.0.0
      - typing-extensions==4.12.2
      - typing-inspection==0.4.0
      - urllib3==1.26.13
      - uvicorn==0.34.0
      - websockets==11.0.3
      - xxhash==3.5.0
      - yarl==1.18.3
